server:
  port: 8181
Spring:
  application:
    name: test
  datasource:
    name: school-manage
    url:  jdbc:mysql://localhost:3306/task
    username: root
    password: root
    driver:
      class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update